// Code generated by protoc-gen-go. DO NOT EDIT.
// source: usergrpc.proto

package generatedclient

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ListUserReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListUserReq) Reset()         { *m = ListUserReq{} }
func (m *ListUserReq) String() string { return proto.CompactTextString(m) }
func (*ListUserReq) ProtoMessage()    {}
func (*ListUserReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_usergrpc_c653ab406bb3c1d5, []int{0}
}
func (m *ListUserReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListUserReq.Unmarshal(m, b)
}
func (m *ListUserReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListUserReq.Marshal(b, m, deterministic)
}
func (dst *ListUserReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListUserReq.Merge(dst, src)
}
func (m *ListUserReq) XXX_Size() int {
	return xxx_messageInfo_ListUserReq.Size(m)
}
func (m *ListUserReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ListUserReq.DiscardUnknown(m)
}

var xxx_messageInfo_ListUserReq proto.InternalMessageInfo

type ListUserResp struct {
	User                 []*User  `protobuf:"bytes,1,rep,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListUserResp) Reset()         { *m = ListUserResp{} }
func (m *ListUserResp) String() string { return proto.CompactTextString(m) }
func (*ListUserResp) ProtoMessage()    {}
func (*ListUserResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_usergrpc_c653ab406bb3c1d5, []int{1}
}
func (m *ListUserResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListUserResp.Unmarshal(m, b)
}
func (m *ListUserResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListUserResp.Marshal(b, m, deterministic)
}
func (dst *ListUserResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListUserResp.Merge(dst, src)
}
func (m *ListUserResp) XXX_Size() int {
	return xxx_messageInfo_ListUserResp.Size(m)
}
func (m *ListUserResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ListUserResp.DiscardUnknown(m)
}

var xxx_messageInfo_ListUserResp proto.InternalMessageInfo

func (m *ListUserResp) GetUser() []*User {
	if m != nil {
		return m.User
	}
	return nil
}

type User struct {
	Id                   int32                `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string               `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Department           string               `protobuf:"bytes,3,opt,name=department,proto3" json:"department,omitempty"`
	Created              *timestamp.Timestamp `protobuf:"bytes,4,opt,name=created,proto3" json:"created,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_usergrpc_c653ab406bb3c1d5, []int{2}
}
func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (dst *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(dst, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetDepartment() string {
	if m != nil {
		return m.Department
	}
	return ""
}

func (m *User) GetCreated() *timestamp.Timestamp {
	if m != nil {
		return m.Created
	}
	return nil
}

type RegisterUserReq struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterUserReq) Reset()         { *m = RegisterUserReq{} }
func (m *RegisterUserReq) String() string { return proto.CompactTextString(m) }
func (*RegisterUserReq) ProtoMessage()    {}
func (*RegisterUserReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_usergrpc_c653ab406bb3c1d5, []int{3}
}
func (m *RegisterUserReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterUserReq.Unmarshal(m, b)
}
func (m *RegisterUserReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterUserReq.Marshal(b, m, deterministic)
}
func (dst *RegisterUserReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterUserReq.Merge(dst, src)
}
func (m *RegisterUserReq) XXX_Size() int {
	return xxx_messageInfo_RegisterUserReq.Size(m)
}
func (m *RegisterUserReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterUserReq.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterUserReq proto.InternalMessageInfo

func (m *RegisterUserReq) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type RegisterUserResp struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterUserResp) Reset()         { *m = RegisterUserResp{} }
func (m *RegisterUserResp) String() string { return proto.CompactTextString(m) }
func (*RegisterUserResp) ProtoMessage()    {}
func (*RegisterUserResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_usergrpc_c653ab406bb3c1d5, []int{4}
}
func (m *RegisterUserResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterUserResp.Unmarshal(m, b)
}
func (m *RegisterUserResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterUserResp.Marshal(b, m, deterministic)
}
func (dst *RegisterUserResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterUserResp.Merge(dst, src)
}
func (m *RegisterUserResp) XXX_Size() int {
	return xxx_messageInfo_RegisterUserResp.Size(m)
}
func (m *RegisterUserResp) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterUserResp.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterUserResp proto.InternalMessageInfo

func (m *RegisterUserResp) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func init() {
	proto.RegisterType((*ListUserReq)(nil), "generatedclient.ListUserReq")
	proto.RegisterType((*ListUserResp)(nil), "generatedclient.ListUserResp")
	proto.RegisterType((*User)(nil), "generatedclient.User")
	proto.RegisterType((*RegisterUserReq)(nil), "generatedclient.RegisterUserReq")
	proto.RegisterType((*RegisterUserResp)(nil), "generatedclient.RegisterUserResp")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserServiceClient interface {
	RegisterUser(ctx context.Context, in *RegisterUserReq, opts ...grpc.CallOption) (*RegisterUserResp, error)
	ListUser(ctx context.Context, in *ListUserReq, opts ...grpc.CallOption) (*ListUserResp, error)
}

type userServiceClient struct {
	cc *grpc.ClientConn
}

func NewUserServiceClient(cc *grpc.ClientConn) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) RegisterUser(ctx context.Context, in *RegisterUserReq, opts ...grpc.CallOption) (*RegisterUserResp, error) {
	out := new(RegisterUserResp)
	err := c.cc.Invoke(ctx, "/generatedclient.UserService/RegisterUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) ListUser(ctx context.Context, in *ListUserReq, opts ...grpc.CallOption) (*ListUserResp, error) {
	out := new(ListUserResp)
	err := c.cc.Invoke(ctx, "/generatedclient.UserService/ListUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
type UserServiceServer interface {
	RegisterUser(context.Context, *RegisterUserReq) (*RegisterUserResp, error)
	ListUser(context.Context, *ListUserReq) (*ListUserResp, error)
}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_RegisterUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterUserReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).RegisterUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/generatedclient.UserService/RegisterUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).RegisterUser(ctx, req.(*RegisterUserReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_ListUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUserReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).ListUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/generatedclient.UserService/ListUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).ListUser(ctx, req.(*ListUserReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "generatedclient.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterUser",
			Handler:    _UserService_RegisterUser_Handler,
		},
		{
			MethodName: "ListUser",
			Handler:    _UserService_ListUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "usergrpc.proto",
}

func init() { proto.RegisterFile("usergrpc.proto", fileDescriptor_usergrpc_c653ab406bb3c1d5) }

var fileDescriptor_usergrpc_c653ab406bb3c1d5 = []byte{
	// 295 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x91, 0x4d, 0x4e, 0xc3, 0x30,
	0x10, 0x85, 0x71, 0x1a, 0xfe, 0x26, 0xa5, 0x45, 0x23, 0x21, 0x45, 0x11, 0x3f, 0x21, 0xab, 0xb0,
	0x71, 0xa5, 0xc0, 0x06, 0x09, 0x0e, 0x80, 0xc4, 0x2a, 0xd0, 0x03, 0xa4, 0xc9, 0x10, 0x59, 0x6a,
	0x12, 0x63, 0xbb, 0xac, 0xb9, 0x11, 0x57, 0x44, 0x71, 0x89, 0x48, 0x5b, 0xa9, 0xd9, 0x79, 0x3c,
	0xef, 0xbd, 0xf1, 0xe7, 0x81, 0xc9, 0x4a, 0x93, 0x2a, 0x95, 0xcc, 0xb9, 0x54, 0x8d, 0x69, 0x70,
	0x5a, 0x52, 0x4d, 0x2a, 0x33, 0x54, 0xe4, 0x4b, 0x41, 0xb5, 0x09, 0x6e, 0xca, 0xa6, 0x29, 0x97,
	0x34, 0xb3, 0xed, 0xc5, 0xea, 0x63, 0x66, 0x44, 0x45, 0xda, 0x64, 0x95, 0x5c, 0x3b, 0xa2, 0x33,
	0xf0, 0x5e, 0x85, 0x36, 0x73, 0x4d, 0x2a, 0xa5, 0xcf, 0xe8, 0x11, 0xc6, 0xff, 0xa5, 0x96, 0x78,
	0x07, 0x6e, 0x3b, 0xc2, 0x67, 0xe1, 0x28, 0xf6, 0x92, 0x0b, 0xbe, 0x95, 0xcf, 0xad, 0xd0, 0x4a,
	0xa2, 0x6f, 0x06, 0x6e, 0x5b, 0xe2, 0x04, 0x1c, 0x51, 0xf8, 0x2c, 0x64, 0xf1, 0x61, 0xea, 0x88,
	0x02, 0x11, 0xdc, 0x3a, 0xab, 0xc8, 0x77, 0x42, 0x16, 0x9f, 0xa6, 0xf6, 0x8c, 0xd7, 0x00, 0x05,
	0xc9, 0x4c, 0x99, 0x8a, 0x6a, 0xe3, 0x8f, 0x6c, 0xa7, 0x77, 0x83, 0x0f, 0x70, 0x9c, 0x2b, 0x6a,
	0x07, 0xf9, 0x6e, 0xc8, 0x62, 0x2f, 0x09, 0xf8, 0x9a, 0x84, 0x77, 0x24, 0xfc, 0xbd, 0x23, 0x49,
	0x3b, 0x69, 0xf4, 0x04, 0xd3, 0x94, 0x4a, 0xa1, 0x0d, 0xa9, 0x3f, 0xa0, 0x1e, 0x00, 0x1b, 0x02,
	0x78, 0x86, 0xf3, 0x4d, 0xf7, 0x06, 0xff, 0x90, 0x3d, 0xf9, 0x61, 0xe0, 0xb5, 0xe5, 0x1b, 0xa9,
	0x2f, 0x91, 0x13, 0xce, 0x61, 0xdc, 0x8f, 0xc3, 0x70, 0xc7, 0xbc, 0xf5, 0xd6, 0xe0, 0x76, 0x40,
	0xa1, 0x65, 0x74, 0x80, 0x2f, 0x70, 0xd2, 0x6d, 0x08, 0x2f, 0x77, 0x0c, 0xbd, 0x5d, 0x06, 0x57,
	0x7b, 0xba, 0x6d, 0xd4, 0xe2, 0xc8, 0xfe, 0xe5, 0xfd, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xd3,
	0x04, 0xca, 0xf9, 0x46, 0x02, 0x00, 0x00,
}
